---
name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print greeting
        run: echo "Hello from GitHub Actions!"

      - name: Print current date and time
        run: echo "Current date and time $(date)"

      - name: Print the branch/tag name
        run: echo "The ref name is ${{ github.ref_name }}"

      - name: List all files in the workspace
        run: |
          echo "Listing all files in the workspace directory:"
          ls -R ${{ github.workspace }} # Lists files recursively from the root of the workspace

      - name: Print OS name (Context Expression)
        run: echo "Operating system is ${{ runner.os }}"


