name: Multi-OS Parallel Check

on:
  workflow_dispatch:

jobs:
  linux-job:
    name: Ubuntu Runner
    runs-on: ubuntu-latest
    steps:
      - name: System Info.
        run: |
          echo "OS Name: ${{ runner.os }}"
          hostname
          whoami
      - name: Check Pre-installed Tool Versions
        run: |
          docker --version
          python3 --version
          node --version
          git --version

  windows-job:
    name: Windows Runner
    runs-on: windows-latest
    steps:
      - name: System Info.
        shell: pwsh
        run: |
          echo "OS Name: ${{ runner.os }}"
          hostname
          whoami
  macos-job:
    name: macOS Runner
    runs-on: macos-latest
    steps:
      - name: System Info.
        run: |
          echo "OS Name: ${{ runner.os }}"
          hostname
          whoami
