name: Global Code Quality

on:
  push:
    branches:
      - main
      - 'release/*'
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Running Linters
        run: echo "This run skipped the docs and focused on the code."


